### ISSUE TITLE
Lack of notifications for Telegram

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [getferdi/ferdi#1081]
**Bug description:**
Telegram service doesn't output notifications or make sounds when messages are received and the Ferdi window is not focused (on a different virtual desktop actually).

Interestingly Telegram does make a sound when I'm adjusting the audio notification volume in Telegram's own settings. 

**Steps to reproduce:**
1. Set up a Teleram service
2. Check that audio (and thus notifications) are enabled in Ferdi
3. Check that sound and notifications are enabled in Telegram service

3. Get a message naturally OR ask someone to send you a message
4. Observe how you get no visual or audio notification.

**Expected behavior**
Receive the visual notification and the audio cue as with other services.

**Screenshots**
N/A

**Environment:**

- Operating System: Kubuntu 18.04 bionic (with KDE 5.47.0 / Plasma 5.12.9 and Kernel: x86_64 Linux 5.4.0-54-generic)
- Ferdi Version: 5.5.0 (x64 via Flatpak)
- Server: Using without an account

- Debug information:

Click this V
<Details>
{"host":{"platform":"linux","release":"5.4.0-54-generic","screens":[{"id":13761487533244482,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":68,"y":0,"width":1852,"height":1080},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:INVALID, transfer:INVALID, matrix:INVALID, range:INVALID}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1852,"height":1080},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"discord","version":"1.1.3"},{"id":"messenger","version":"1.1.0"},{"id":"riot","version":"1.0.3"},{"id":"skype","version":"1.3.0"},{"id":"slack","version":"1.0.15"},{"id":"steamchat","version":"1.1.2"},{"id":"telegram","version":"3.0.0"},{}],"devRecipes":[],"services":[{"id":"6d820ca3-4ae0-4ec7-b690-f8ea50e3cd6d","recipe":"messenger","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"c6ae2f2a-393c-4aed-a796-09b54d06b1b7","recipe":"telegram","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"915dd32d-55b8-41a1-84f2-7fe16b993c67","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"6e64d741-0708-4b18-8b6d-0b930938f303","recipe":"riot","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"481546b8-47d6-4bb0-9526-44408cd24c6c","recipe":"discord","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"1a490ee1-0f77-4046-a475-ce8496069fe0","recipe":"skype","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"13b627ce-488e-43c9-ad19-8fa0bde8dce7","recipe":"steamchat","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"}],"workspaces":[],"windowSettings":{"width":800,"height":600,"x":0,"y":0,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080},"isMaximized":true,"isFullScreen":false},"settings":{"autoLaunchInBackground":false,"runInBackground":false,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":"","privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":true,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":"30","sentry":true,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}
</Details>
During this session of Ferdi I sent and received messages on Telegram (which should have resulted in notifications). Temporarily disabled other services to not leak personal information here.

**Comment by mastercko** [comment]
I had this same problem on Windows 10 Pro. I had to remove it and use standalone Telegram because I am in a situation where I absolutely need those notifications to show up.

**Comment by kgilbert89** [comment]
I'm having a similar issue on Windows 10.  I don't get popups but I do still get the sound notifications.

**Comment by giuseppeperelli** [comment]
I have exactly the same issue with my Facebook Messenger service. I run Ferdi on

**Comment by cocoonkid** [comment]
Same here with Arch Linux 5.9.


noticed that ferdi does not appear in the list of applications for notifications in the xfce notifications menu.

So I think it just does not get registered there.

**Comment by vraravam** [comment]
With the latest version of Ferdi and the latest recipes, this should no longer be the case.

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by mhatvan** [comment]
@i-need-to-tell-you-something With `5.6.0-nightly.71` and the `telegram-react` recipe (not `telegram`) I receive notifications as expected on macOS. Can you try the same?

**Comment by i-need-to-tell-you-something** [comment]
On Ferdi 5.5.0 (via flatpak) using the `telegram-react` recipe from the app I receive the notifications as expected as well - sound pings, numberless red badge on the tray icon, numbered badge in the app on the service icon. The `telegram` recipe no longer even loads for me.

I guess if the `telegram` service is not supposed to work, then this issue can be closed.

**Comment by vraravam** [comment]
Closing the issue since this has been fixed in the latest nightlies with the updated service recipes.

**Comment by Silun** [comment]
I am experiencing this issue on version 5.6.0 with the new Telegram web (K + Z) client. When ferdi is opened, on the Z version it sometimes marks messages as read even though it's not in focus (but maximized on one screen), which prevents the notification on the phone.

I don't know when this started, but I noticed that I wasn't noticing a lot of the messages I get in a day and found out that Ferdi's Telegram is not playing notification sounds and sometimes just plain marks the messages as read when not in focus.

**Comment by vraravam** [comment]
@Silun - please try out the `Telegram-react` service recipe. Unfortunately, the telegram recipe does not seem to work seamlessly and I have never gotten it to work for me ever.

**Comment by Silun** [comment]
I didn't have a telegram-react recipe in the recipe folder, so I downloaded it from github and put the folder there manually. It works fine for logging in and messaging, the only difference I notice is a slightly different color palette.

The audio is still missing, though. No sound for Telegram whatsoever. I double checked and audio is enabled for the service(s).

Thank you for the very timely response!

**Comment by vraravam** [comment]
Could you please try with the nightlies? They are quite stable I can assure you.

If you don't see the `telegram-react` service recipe - then I am not sure that you are running the latest version of Ferdi (5.6.0 is the minimum version that we can support).

Unless you have created or edited any recipe, please do not use recipes by downloading - though that is "supported", its quite difficult for us to debug and roll-out any fixes.

**Comment by Silun** [comment]
Well, it says there are no updates when I perform a check. I remember that there was something about not being able to push new releases, but that was 5.5.0 IIRC and I thought it got fixed :)

I will try a nightly and see how it goes.

**Comment by vraravam** [comment]
The in-app updater for Ferdi is broken atm. The recipes get updated only if the main app itself is updated.

Decoupling of updates to recipes is an idea that I have floated as a discussion point which you can vote for.
