### ISSUE TITLE
Ferdi crashes on startup

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1263]
**Bug description:**
I have been using Ferdi nightlies for the past few months. Since the past 24 hours (not exactly sure of the exact time), Ferdi crashes whenever its restarted. Based on my setup, I have narrowed it down to the following folder: `Library/Application\ Support/Ferdi/Partitions` being the culprit. ie when i blast away this folder, and restart Ferdi, it starts up and stays up.

I dont think I have made any changes in the recent past few days - so, there's no setting or something that is corrupted on my client side (ie on local laptop) - might be something else.

**Steps to reproduce:**

1. Install Ferdi nightly 15
2. Configure some services
3. Quit Ferdi
4. Restart - and it crashes

**Expected behavior**
Ferdi restarts successfully, 

**Screenshots**

**Environment:**

- Operating System: macos Big Sur 11.2.3
- Ferdi Version: 5.6.0-nightly.15
- Server: Ferdi

- Debug information:

Unable to get debug information since Ferdi crashes on startup

**Comment by vraravam** [comment]
Update: I deleted all the registered services, and was able to restart Ferdi (It came up and stayed on the "Get Started" screen).

Update 2: I have added only 1 single service "Gmail"- and restarts work smoothly now.

**Comment by vraravam** [comment]
*Debug Information* (Please remember that this is *after* the previous updates, and recreation of all registered services - so might not be completely accurate about past crashes information:
{"host":{"platform":"darwin","release":"20.3.0","screens":[{"id":69733632,"bounds":{"x":0,"y":0,"width":1680,"height":1050},"workArea":{"x":0,"y":25,"width":1680,"height":1025},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":30,"colorSpace":"{primaries:SMPTEST432_1, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":10,"size":{"width":1680,"height":1050},"workAreaSize":{"width":1680,"height":1025},"scaleFactor":2,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.0-nightly.15","electron":"10.2.0","installedRecipes":[{"id":"android-messages","version":"1.3.0"},{"id":"franz-custom-website","version":"1.0.2"},{"id":"github","version":"2.0.0"},{"id":"gitlab","version":"1.0.0"},{"id":"gmail","version":"1.3.5"},{"id":"googlecalendar","version":"1.0.3"},{"id":"hangoutschat","version":"1.4.0"},{"id":"telegram","version":"3.0.0"},{"id":"telegram-react","version":"1.0.1"},{"id":"whatsapp","version":"2.0.8"},{"id":"yahoo-mail","version":"1.0.0"},{}],"devRecipes":[],"services":[{"id":"86b5ee3b-35c4-4c86-b626-d5e76000da12","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"5c9efb4f-d247-4214-90d3-4eb035f09721","recipe":"gmail","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"d458ab52-0583-4c18-b048-1e3e804f1d09","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"7c620993-64f1-4ac9-b231-e09d06d433dc","recipe":"hangoutschat","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"2a842377-5bed-4aa5-bc28-870b18014530","recipe":"android-messages","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"c18f7665-171a-4037-9ffe-37e3165b9696","recipe":"googlecalendar","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"be02b66c-11f4-4a7d-b998-93ca15cb42b9","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"24df9179-d524-4a27-be8f-77f93f81e789","recipe":"github","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"34dbed2e-8879-42b0-99b1-38761d8aa1a0","recipe":"gitlab","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"4ffdd8bd-d79f-4bd9-af6b-21d6e461c5a9","recipe":"yahoo-mail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"}],"workspaces":[{"id":"13db4596-2719-49e0-8b0a-573d67fed719","services":[null,null,null,null]},{"id":"52d7ecc6-19d7-42ee-bb07-f19aa5d2cd38","services":[null,null,null,null,null,null]}],"windowSettings":{"width":800,"height":600,"x":0,"y":25,"isMaximized":true,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1680,"height":1050}},"settings":{"autoLaunchInBackground":false,"runInBackground":false,"reloadAfterResume":true,"enableSystemTray":false,"startMinimized":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"notifyTaskBarOnMessage":true,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"en-us\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#1974fc","serviceRibbonWidth":"45","iconSize":"20","sentry":true,"nightly":true,"navigationBarBehaviour":"always","useVerticalStyle":false,"alwaysShowWorkspaces":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by vraravam** [comment]
Update: One trick that I found to overcome the startup-crash is for me to *very quickly, AND randomly* use the `Cmd+<number>` shortcut keys to blazingly switch between all the configured services. This somehow automagically overcomes the crash scenario - and Ferdi stays open and responsive. Keeping this issue open with this important update - in case its helpful for others, and/or it triggers a random thought on one of the contributors for a definitive fix.

**Comment by binarymelon** [comment]
Has anyone tried Franz lately?  The stability of Ferdi is just unacceptable.  I use this for my job so I'm going to have to move to something that actually works, regardless of the cost.

**Comment by vraravam** [comment]
@binarymelon - could you please specify which version of Ferdi you are using and which OS?

Publishing of the nightlies have been broken for some time (but, I suspect @kytwb will come with some good news in the next couple of hours to fix the expired certificate issue - which will unblock the nightlies from tonight. 🤞🏼)

We are actively putting lots of bug fixes, and feature enhancements to Ferdi - but, I do realize that an unstable app is no fun to use for anyone. That being said, I am building from source and have published working versions in a gDrive folder - please checkout the project README on where to download for macos/linux.

**Comment by binarymelon** [comment]
5.6.0-nightly.15 (Windows 10)
@vraravam 's workaround also worked for me (took a couple of attempts).  Otherwise I need to blow away my app data folders and setup again and that will usually fix things for a couple of weeks, until the problem starts again.  I have had this problem on the latest stable, beta and nightly over the last few months.

**Comment by ylluminate** [comment]
This is stable for me with several services on macOS 10.15.7 aside from a Renderer crash that doesn't seem to happen but at startup and doesn't stop the app: https://github.com/getferdi/ferdi/issues/366

**Comment by vraravam** [comment]
I have just published the unsigned versions of Ferdi in [my fork](https://github.com/vraravam/nightlies/releases) - in case anyone wants to try it out.

**Comment by ylluminate** [comment]
@vraravam are you referring to my issue or another (or both)?

**Comment by vraravam** [comment]
@ylluminate - I was referring to the "this is stable...doesn't stop the app" comment. Excepting for the fact that I still need to do [this](https://github.com/getferdi/ferdi/issues/1263#issuecomment-830636673) - the app itself is quite stable, and working good for all my usecases.

**Comment by ylluminate** [comment]
@vraravam hmm, alright - fwiw, I tried your nightly and am still having the `Renderer` crash and I even tried updating to Big Sur here and am still having the crash.

**Comment by vraravam** [comment]
yes @ylluminate - the "crash on startup" issue is still present - im unable to get a dump of the startup sequence to be able to then track the location of the crash. till then, the random clicking of the sidebar to switch between various services is the way to go (for now).

**Comment by fuzzy76** [comment]
Seeing this too, on 5.6.0-nightly.57

Crashlog: https://gist.github.com/fuzzy76/f099d861131630a89a19e99b69deb842

**Comment by ylluminate** [comment]
@vraravam where will we be able to find the main nightlies going forward?

**Comment by vraravam** [comment]
You can find them [here](http://github.com/getferdi/nightlies/releases)

**Comment by keunes** [comment]
@vraravam Could I try the nightly builds also on Ubuntu to see if this issue is fixed for me too? (I understood that the nightly builds work for Mac, not for Windows, but there was no word on Linux.)

**Comment by vraravam** [comment]
@keunes - please go ahead. The latest nightlies are here:  https://github.com/getferdi/nightlies/releases (as mentioned by @ylluminate )

**Comment by fuzzy76** [comment]
This still happens on 5.6.0-nightly.72 :-/

```
Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [6869]
```

**Comment by keunes** [comment]
I have nightly 71 on Ubuntu and it no longer crashes on start. Two differences though: previously I installed through Flatpak and now with a DEB, and (consequently) all my services were gone so I'm starting with a clean slate.

**Comment by vraravam** [comment]
This was still crashing for me, but one important change that I had done was:
Previously, I was logging into Ferdi with an account based on api.ferdi.com - but, for a different reason, I had switched all my services to "login without an account" ie using the local standalone server. Now, ,I *never* have a crash. Maybe this will help isolate the area of investigation.

**Comment by fuzzy76** [comment]
I use api.getferdi.com and it is still happening on close to every launch. The cmd-numbers trick works though.

**Comment by drydenmike** [comment]
This crash on launch is still happening.
I'm running Ferdi-5.6.0 on Windows 10 and the only workaround I found so far is to delete the "recipes" folder form appdata and Ferdi recreates it on launch and doesn't crash (and don't worry it wont ask you to login in your services again).
Still it's a pain doing this every time, so I'm launching it trough a script that deletes the folder 1st and launches it next.

**Comment by vraravam** [comment]
@drydenmike - i suspect some other form of corruption in your ferdi profile. Is it possible for you to start afresh (backup your old profile folder in case the issue isn't resolved and you want to get back in without signing again).

Also, are you using Ferdi with a Ferdi/Franz login or without a server?

**Comment by drydenmike** [comment]
@vraravam I've tried uninstalling and reinstalling (deleting all data in between) and now I'm even using the portable version and it still happens. 
I'm using in 2 different W10 (1 desktop and 1 laptop) an this behavior happens in both of them.
I'm logged in Ferdi.

**Comment by vraravam** [comment]
Thanks for getting back. Could I request you to try without the server? ie Use Ferdi without a login? I recently (a few months ago) moved away from the hosted Ferdi server and to this server-less usage. And the crash on startup has completely gone. I had logged this bug at that time - and since then I had also commented on this: https://github.com/getferdi/ferdi/issues/1263#issuecomment-877764991

**Comment by drydenmike** [comment]
@vraravam you're right, starting it without a login solves the issue...
I've deleted all appdata and configured it again without login and the crash on boot issue doesn't happen anymore.

**Comment by vraravam** [comment]
thanks for confirming @drydenmike . For resurrecting your old services/workspaces, you can always login in youor browser to the [server](http://getferdi.com) and export all the data. Then you can import the same by visiting [this url](http://localhost:45569/) - which is where Ferdi "stores it locally" if using without a server.

**Comment by boschkundendienst** [comment]
+1 on Windows with

Version: 5.6.0
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
Platform: Windows 10
Arch: x64
Build date: Sun Jul 18 2021 17:13:02 GMT+0200 (Central European Summer Time)
Git SHA: 7b09fe7
Git branch: release

**Comment by vraravam** [comment]
> it would be a good idea to expose such a url via a menu item - and I am just about the commit the changes for the same!

Circling back on this, such a menu item is present: `Help > Import/Export Configuration data`
