### ISSUE TITLE
No requests about microphone or camera access on macOS

### ISSUE THREAD

**Issue by pztrn** [getferdi/ferdi#154]
Title says everything. When I tried to call via Discord or Riot there is no microphone or camera access requests at all, resulting in failed call in Riot and being "silenced listener" on Discord.

macOS 10.15, Ferdi 5.4.0-beta.2 from releases page.

**Comment by vantezzen** [comment]
I'm currently merging Franz 5.4.0 into Ferdi and the requests pop up there. 
It will be published the next couple of days - can you then please test if if works for you too?
I'll leave this issue open until then.

**Comment by vantezzen** [comment]
We have released Ferdi 5.4.0-beta.4 now. Could you please update to this version and try again?

**Comment by pztrn** [comment]
Well... :D 

[ferdi-traces.log](https://github.com/getferdi/ferdi/files/3776098/ferdi-traces.log)

**Comment by pztrn** [comment]
Tried to delete app's data, re-login, and no, isn't working. No requests for webcam/microphone access and no a/v in Discord and Riot.

**Comment by vantezzen** [comment]
You are on beta.4? Hmm, can't find anything in the logs you send either.

**Comment by pztrn** [comment]
Yes it was from beta.4 when I try to launch Ferdi with services that was created on beta.2. Something went wrong here.

Actually, I've re-logged into Ferdi (using self-hosted server), first login went fine, but I can't start it anymore - something went wrong with logs from above. I'll create another issue for that.

Main issue still unresolved - no requests, no a/v.

**Comment by kytwb** [comment]
I'll be taking a look at it today 🙏

**Comment by vantezzen** [comment]
Related: https://electronjs.org/docs/api/system-preferences#systempreferencesaskformediaaccessmediatype-macos

**Comment by ammarmalhas** [comment]
Sorry I know nothing about the programing but v5.4.0 Beta 4 still does not ask for Mic/Camera permission! Is there a way to allow this until it is fixed in a new update?

**Comment by kytwb** [comment]
@vantezzen thanks for the tip!
@ammarmalhas I'm on it will update this issue when fixed and shipped.

**Comment by kytwb** [comment]
Other things got on the way. I am still working on this one. It is working in development, but not in the production app. Still investigating macOS entitlements.

**Comment by kytwb** [comment]
@pztrn @ammarmalhas The pull request addressing this issue has been merged; it should work as expected in the next release. Thanks for your patience! 🙏

**Comment by ylluminate** [comment]
FYI, having this in Mattermost as well where audio recording via [a plugin such as this](https://github.com/streamer45/mattermost-plugin-voice) will not function. Looking forward to the next build.

**Comment by kytwb** [comment]
Shipped in [v5.4.1-beta.4](https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.4).

**Comment by ylluminate** [comment]
Audio recording works great in Ferdi now!
