### ISSUE TITLE
No red dot for new message in Discord

### ISSUE THREAD

**Issue by BHMath** [getferdi/ferdi#319]
**Describe the bug**
I don't see red dot for new message in discord

**To Reproduce**
Connect to discord and have somenew mlessage to read

**Expected behavior**
See red dot when new message are available

**Desktop (please complete the following information):**

- OS: Windows 10 or 7
- Version 5.4.0

**Comment by vantezzen** [comment]
Related:
https://github.com/meetfranz/recipe-discord/issues/19
https://github.com/meetfranz/franz/issues/1521

We could think about adding the fix from https://github.com/Sauceee/recipe-discord/blob/master/webview.js to the recipe

**Comment by vantezzen** [comment]
I just merged the fix I mentioned above into the recipe repository - the updated recipe should be available in the next update of Ferdi.

**Comment by klocus** [comment]
This issue is still not fixed.

**Comment by camslice** [comment]
Bump

**Comment by mhatvan** [comment]
Closing due to inactivity.

**Comment by ylluminarious** [comment]
@mhatvan @vantezzen It appears that this is still an issue: https://github.com/getferdi/ferdi/issues/1915

Perhaps this should be re-opened?
