### ISSUE TITLE
Persistent authentication problem notice on Gmail

### ISSUE THREAD

**Issue by SauceCodeFr** [getferdi/ferdi#320]
**Describe the bug**
I am having an authentication problem notice on top of Gmail. It cannot be removed and stay persistent.

**To Reproduce**
I just added a new service Gmail, logged in, and I have this message. Trying to delete the service and adding it again does not solve the issue (is a cache stay in Ferdi after deleting a service ?)

For information i am using google double authentication with my smartphone ... Maybe this is the problem (at the connection the double auth was successful, no problem on this side).

**Screenshots**
![Capture](https://user-images.githubusercontent.com/1242308/72883072-f3a38e80-3d03-11ea-8020-ce5d5b5305ef.PNG)

**Desktop (please complete the following information):**
- OS: Windows 10

**Comment by Dunkh4n** [comment]
Same here..

**Comment by julienfortinfr** [comment]
Hi,
I got the same problem, unable to log in gmail.com
Thanks for your help,
Best regards,
julien
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/25707525/74092792-64e78d80-4ac9-11ea-9d17-6ab6c3e8b9bc.png">

**Comment by vantezzen** [comment]
@julienfortinfr The bug you are experiencing is actually a different one and should be fixed by updating to the newest beta version of Ferdi.

**Comment by REBELinBLUE** [comment]
I get the same thing, don't have this happen in Franz

**Comment by julienfortinfr** [comment]
@vantezzen Thank you, I'll try the beta.

**Comment by bzsimon** [comment]
> @julienfortinfr The bug you are experiencing is actually a different one and should be fixed by updating to the newest beta version of Ferdi.

I've try with the last beta releas of Ferdi, but the login problem and "unsafe Browser" still persist...
Best regards

**Comment by alapo** [comment]
> > @julienfortinfr The bug you are experiencing is actually a different one and should be fixed by updating to the newest beta version of Ferdi.
> 
> I've try with the last beta releas of Ferdi, but the login problem and "unsafe Browser" still persist...
> Best regards

I can confirm that this is occuring with Ferdi 5.4.4-beta.2. I am unable to log-into my YouTube service at the moment (I get the same error as @bzsimon )

**Comment by Brotater** [comment]
I was able to fix this by updating the gmail recipe index.js to the following:
`module.exports = Franz =>
  class Gmail extends Franz {
    overrideUserAgent() {
      return "Chrome/70.0.3538.77";
    }
  };
`

Some other solutions updated this to the firefox user agent, but that still caused the issue for me.  Once I updated this to Chrome only, the error went away.

**Comment by vraravam** [comment]
I'm on the latest beta (Version 5.4.4-beta.3 (5.4.4-beta.3.1426)) - and I am unable to find the `~/.config/Ferdi` folder - so, can't change it. Any help please?

**Comment by Brotater** [comment]
If you're on a mac: `~/Library/Application Support/Ferdi/recipes/gmail`

**Comment by vraravam** [comment]
Thanks @Brotater - this is working now! Now I just need to write up a script that I can use if/when this occurs again. (since I use `homebrew` to upgrade to beta versions of ferdi as soon as one's released!)

**Comment by kytwb** [comment]
I don't think this is happening anymore in newer versions (at least since 5.5.0-gm). Closing for now 🙏
